name: Pull request
on:
  pull_request:
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-lint:
    name: Rust Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-builder-cache@v2
        with:
          shared-key: rust-builder-lint
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --tests --all-targets --all-features --locked -- -D warnings -D clippy::all -D clippy::print_stdout -D clippy::print_stderr

  rust-test:
    name: Rust Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-builder-cache@v2
        with:
          shared-key: rust-builder-test
      - name: Test
        run: cargo test --workspace --all-targets --all-features --locked

  rust-build:
    name: Rust Build
    runs-on: ubuntu-latest
    needs:
      - rust-builder
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Artifact Tag
        id: artifact_tag
        run: echo tag=$(cargo pkgid --locked auth | xargs basename | sed s/#/-v/) >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ secrets.DOCKERHUB_REPO }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=pr,prefix=${{ steps.artifact_tag.outputs.tag }}-pr-
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            BASE_IMAGE=rust-builder-${{ env.GITHUB_SHA }}
            BIN=${{ matrix.bin }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  rust-builder:
    name: Rust Builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Cargo.lock Hash
        id: cargo_lock_hash
        run: echo hash=$(md5 -q Cargo.lock) >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ secrets.DOCKERHUB_REPO }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=rust-builder-${{ steps.cargo_lock_hash.outputs.hash }}
            type=raw,value=rust-builder-${{ env.GITHUB_SHA }}
      - name: Build and Push Rust Builder
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

