name: Release
concurrency: release
on:
  push:
    branches:
      - main

jobs:
  release-image:
    name: Release Image
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        bin:
          - auth
    steps:
      - uses: actions/checkout@v3
      - uses: jwalton/gh-find-current-pr@v1
        id: find_pr
        with:
          state: closed
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Image Tags
        id: image_tags
        run: |
          export TAG=$(cargo pkgid --locked auth | xargs basename | sed s/#/-v/)
          echo source_tag=$TAG-pr-${{ steps.find_pr.outputs.pr }} >> $GITHUB_OUTPUT
          echo target_tag=$TAG >> $GITHUB_OUTPUT
      - name: Release Image
        run: |
          docker pull ${{ secrets.DOCKERHUB_REPO }}:${{ steps.image_tags.outputs.source_tag }}
          docker tag ${{ secrets.DOCKERHUB_REPO }}:${{ steps.image_tags.outputs.source_tag }} ${{ secrets.DOCKERHUB_REPO }}:${{ steps.image_tags.outputs.target_tag }}
          docker push ${{ secrets.DOCKERHUB_REPO }}:${{ steps.image_tags.outputs.target_tag }}
