name: Release
concurrency: release
on:
  push:
    branches:
      - main

jobs:
  release-image:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        bin:
          - auth
    steps:
      - uses: actions/checkout@v3
      - name: Get Image Tags
        id: image_tags
        run: |
          export TAG=$(cargo pkgid --locked auth | xargs basename | sed s/#/-v/)
          echo source_tag=$TAG-$GITHUB_SHA >> $GITHUB_OUTPUT
          echo target_tag=$TAG >> $GITHUB_OUTPUT
      - name: Release Image
        run: docker tag ${{ secrets.DOCKERHUB_TOKEN }}:${{ steps.image_tags.outputs.source_tag }} ${{ secrets.DOCKERHUB_TOKEN }}:${{ steps.image_tags.outputs.target_tag }}
